server:
  Port: :5050

postgres:
  PostgresqlHost: "" # from env variables
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: edriver
  PostgresqlSslmode: disable
  PostgresqlDriver: postgres

redis:
  RedisHost: "" # from env variables
  Password: ""
  DB: 0

cookie:
  Name: refreshToken
  MaxAge: 43200
  Path: /
  Secure: false
  HttpOnly: true

tokensTTL:
  Access: 15
  Refresh: 43200
