name: Build

on: push

jobs:

  build:
    strategy:
      matrix:
         go: ["1.16.x", "1.17.x"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./cmd/app/main.go
